{% set name = "nomad-camels-driver-cam-control-pylablib" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nomad_camels_driver_cam_control_pylablib-{{ version }}.tar.gz
  sha256: cbd0339dcad48ca27a557bdcda70c7aa0ca94542778aadc9bc3077c304491842

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9.6
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9.6
    - nomad-camels >=0.2

test:
  imports:
    - nomad_camels_driver_cam_control_pylablib

about:
  home: https://github.com/FAU-LAP/CAMELS_drivers
  summary: This packes allows you to connect to Cam-Control by pylablibs.
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
